apiVersion: apps/v1
kind: Deployment
metadata:
  name: typescript-worker
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typescript-worker
  template:
    metadata:
      labels:
        app: typescript-worker
    spec:
      containers:
      - name: typescript-worker
        image: ${REGISTRY}/typescript-worker:latest
        env:
        - name: TEMPORAL_HOST
          value: temporal-frontend.temporal.svc.cluster.local:7233
        - name: TEMPORAL_NAMESPACE
          value: default
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 