concurrent = 4
[[runners]]
name = "myRunner"
url = "http://git.home/ci"
token = "glrt-t3_vQ5uxpatptAGHBa9WiG8"
executor = "docker"
[runners.docker]
  tls_verify = true
  image = "ubuntu:latest"
  privileged = true
  disable_entrypoint_overwrite = false
  oom_kill_disable = false
  disable_cache = false
  volumes = [
    "/cache",
  ]
  shm_size = 0
  allowed_pull_policies = ["always", "if-not-present"]
  allowed_images = ["*/*/*/*:*", "*/*/*:*", "*/*:*", "*:*", "docker:*", "docker:*:*"]
  allowed_services = ["*/*/*:*", "*/*:*", "*:*", "docker:*", "docker:*:*", "docker:*:*:*"] 