# pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.69.84-192.168.69.98
---
# advertisement
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example-advertisement
  namespace: metallb-system