# MetalLB IP Address Pool Configuration
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.69.95-192.168.69.100  # Adjust this range as needed
---
# MetalLB L2 Advertisement Configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - main-ip-pool
