# Python Temporal Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-worker
  namespace: temporal
  labels:
    app: python-worker
    component: worker
    language: python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-worker
  template:
    metadata:
      labels:
        app: python-worker
        component: worker
        language: python
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: python-worker
        image: git.home:5050/mike/proxmox-k8s-infra/python-worker:latest
        env:
        - name: TEMPORAL_HOST
          value: temporal-frontend.temporal.svc.cluster.local:7233
        - name: TEMPORAL_NAMESPACE
          value: default
        - name: WORKER_TASK_QUEUE
          value: python-task-queue
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - python
            - -c
            - "import sys; sys.exit(0)"
          initialDelaySeconds: 10
          periodSeconds: 10
