# Go Temporal Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-worker
  namespace: temporal
  labels:
    app: go-worker
    component: worker
    language: go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-worker
  template:
    metadata:
      labels:
        app: go-worker
        component: worker
        language: go
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: go-worker
        image: git.home:5050/mike/proxmox-k8s-infra/go-worker:latest
        env:
        - name: TEMPORAL_HOST
          value: temporal-frontend.temporal.svc.cluster.local:7233
        - name: TEMPORAL_NAMESPACE
          value: default
        - name: WORKER_TASK_QUEUE
          value: go-task-queue
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep go-worker"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep go-worker"
          initialDelaySeconds: 10
          periodSeconds: 10
