# C# Temporal Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-worker
  namespace: temporal
  labels:
    app: csharp-worker
    component: worker
    language: csharp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csharp-worker
  template:
    metadata:
      labels:
        app: csharp-worker
        component: worker
        language: csharp
    spec:
      imagePullSecrets:
      - name: gitlab-registry-secret
      containers:
      - name: csharp-worker
        image: git.home:5050/mike/proxmox-k8s-infra/csharp-worker:latest
        env:
        - name: TEMPORAL_HOST
          value: temporal-frontend.temporal.svc.cluster.local:7233
        - name: TEMPORAL_NAMESPACE
          value: default
        - name: WORKER_TASK_QUEUE
          value: csharp-task-queue
        - name: DOTNET_ENVIRONMENT
          value: Production
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - dotnet
            - --info
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - dotnet
            - --info
          initialDelaySeconds: 10
          periodSeconds: 10
